const regexHeaderComment = `Do not edit this file!!!

The file "src/regex_editable.ts" contains the source for this regex and is transformed by "babel-plugin-transform-regex".
Run "npm run build:regex" to generate this file again afer editing the source.`;

module.exports = {
	presets: ["@babel/preset-typescript"],
	plugins: [
		[
			"babel-plugin-transform-regex",
			{
				removeImport: true,
				headerComment: regexHeaderComment,
				disableUnicodeSets: true, // can be removed after node 18 support is dropped
			},
		],
	],
};
